#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep of 2 seconds.
# It reacts to SIGTERM by displaying "I am invincible!!!"

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
